language: java
jdk:
 - oraclejdk8
before_install:
#  - mvn install -Dmaven.javadoc.skip=true
   - "echo skipped"
install:
  - "echo skipped"
script:
  - "echo skipped"
#  - mvn install -Dmaven.javadoc.skip=true
# - mvn deploy